[project]
name = "age-estimation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kai Riegler", email = "101566944+KaiRiegler@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pillow>=12.3.0",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu132", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu132", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true

[project.scripts]
age-estimation = "age_estimation:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "jupyterlab>=4.6.4",
    "pytest>=9.1.1",
]
